-- Data for CRMS_MODULE_GROUPS. Generated rows: 3
SET DEFINE OFF
INSERT INTO "CRMS_MODULE_GROUPS" ("MODULE_ID", "GROUP_ID") VALUES (2, 3);
INSERT INTO "CRMS_MODULE_GROUPS" ("MODULE_ID", "GROUP_ID") VALUES (3, 1);
INSERT INTO "CRMS_MODULE_GROUPS" ("MODULE_ID", "GROUP_ID") VALUES (4, 2);
COMMIT;
