-- CRMS_ASSIGNMENT_GROUPS
CREATE TABLE "CRMS_ASSIGNMENT_GROUPS" 
   (	"GROUP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"GROUP_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("GROUP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_GROUP_NAME" UNIQUE ("GROUP_NAME")
  USING INDEX  ENABLE
   ) ;
