-- CRMS_MODULES
CREATE TABLE "CRMS_MODULES" 
   (	"MODULE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MODULE_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(500), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("MODULE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_MODULE_NAME" UNIQUE ("MODULE_NAME")
  USING INDEX  ENABLE
   ) ;
