-- CRMS_APPROVAL_GROUPS
CREATE TABLE "CRMS_APPROVAL_GROUPS" 
   (	"AG_MAP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"COMPANY_NAME" VARCHAR2(200), 
	"SERVICE_NAME" VARCHAR2(200), 
	"MODULE_ID" NUMBER, 
	"GROUP_ID" NUMBER NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20) DEFAULT 'RD' NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"LEVEL_ORDER" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	 PRIMARY KEY ("AG_MAP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_APGRP_MOD" FOREIGN KEY ("MODULE_ID")
	  REFERENCES "CRMS_MODULES" ("MODULE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_APGRP_GRP" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "CRMS_ASSIGNMENT_GROUPS" ("GROUP_ID") ON DELETE CASCADE ENABLE
   ) ;
CREATE INDEX "IDX_APGRP_COMPANY" ON "CRMS_APPROVAL_GROUPS" ("COMPANY_NAME") 
  ;

CREATE INDEX "IDX_APGRP_LEVEL" ON "CRMS_APPROVAL_GROUPS" ("PHASE_CODE", "LEVEL_ORDER") 
  ;

CREATE INDEX "IDX_APGRP_MODULE" ON "CRMS_APPROVAL_GROUPS" ("MODULE_ID") 
  ;
