-- CRMS_MODULE_GROUPS
CREATE TABLE "CRMS_MODULE_GROUPS" 
   (	"MODULE_ID" NUMBER NOT NULL ENABLE, 
	"GROUP_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_MODULE_GROUPS" PRIMARY KEY ("MODULE_ID", "GROUP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_MG_MODULE" FOREIGN KEY ("MODULE_ID")
	  REFERENCES "CRMS_MODULES" ("MODULE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_MG_GROUP" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "CRMS_ASSIGNMENT_GROUPS" ("GROUP_ID") ON DELETE CASCADE ENABLE
   ) ;
