-- CRMS_PHASE_GROUPS
CREATE TABLE "CRMS_PHASE_GROUPS" 
   (	"PHASE_GROUP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MODULE_ID" NUMBER NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"GROUP_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("PHASE_GROUP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_PG_PHASE" CHECK (phase_code IN ('DRAFT','RD','FSD','DEV','TESTING','UAT','DEPLOYMENT','DBA_DEPLOYMENT','OBSERVATION')) ENABLE, 
	 CONSTRAINT "FK_PG_MODULE" FOREIGN KEY ("MODULE_ID")
	  REFERENCES "CRMS_MODULES" ("MODULE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_PG_GROUP" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "CRMS_ASSIGNMENT_GROUPS" ("GROUP_ID") ENABLE
   ) ;
CREATE INDEX "IDX_PG_MODULE" ON "CRMS_PHASE_GROUPS" ("MODULE_ID") 
  ;
