-- CRMS_SERVICES
CREATE TABLE "CRMS_SERVICES" 
   (	"SERVICE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"SERVICE_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("SERVICE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_SERVICE_NAME" UNIQUE ("SERVICE_NAME")
  USING INDEX  ENABLE
   ) ;
