-- CRMS_COMPANY_GROUP_PHASE_MAP
CREATE TABLE "CRMS_COMPANY_GROUP_PHASE_MAP" 
   (	"PHASE_MAP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"COMPANY_ID" NUMBER NOT NULL ENABLE, 
	"SERVICE_ID" NUMBER NOT NULL ENABLE, 
	"GROUP_ID" NUMBER NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("PHASE_MAP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_COMPANY_SERVICE_GROUP_PHASE" UNIQUE ("COMPANY_ID", "SERVICE_ID", "GROUP_ID", "PHASE_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_CGPM_PHASE" CHECK (phase_code IN ('ALL','RD','FSD','DEV','TESTING','UAT','DEPLOYMENT','DBA_DEPLOYMENT','OBSERVATION')) ENABLE, 
	 CONSTRAINT "FK_CGPM_COMPANY" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "CRMS_COMPANIES" ("COMPANY_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_CGPM_SERVICE" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "CRMS_SERVICES" ("SERVICE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_CGPM_GROUP" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "CRMS_ASSIGNMENT_GROUPS" ("GROUP_ID") ON DELETE CASCADE ENABLE
   ) ;
CREATE INDEX "IDX_CGPM_CO_SVC" ON "CRMS_COMPANY_GROUP_PHASE_MAP" ("COMPANY_ID", "SERVICE_ID") 
  ;
