-- CRMS_COMPANY_SERVICE_MAP
CREATE TABLE "CRMS_COMPANY_SERVICE_MAP" 
   (	"MAP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"COMPANY_ID" NUMBER NOT NULL ENABLE, 
	"SERVICE_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("MAP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_COMPANY_SERVICE" UNIQUE ("COMPANY_ID", "SERVICE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CSM_COMPANY" FOREIGN KEY ("COMPANY_ID")
	  REFERENCES "CRMS_COMPANIES" ("COMPANY_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_CSM_SERVICE" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "CRMS_SERVICES" ("SERVICE_ID") ON DELETE CASCADE ENABLE
   ) ;
