-- CRMS_USERS
CREATE TABLE "CRMS_USERS" 
   (	"USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"INITIALS" VARCHAR2(3) NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(10) DEFAULT 'user' NOT NULL ENABLE, 
	"PASSWORD_HASH" VARCHAR2(255) NOT NULL ENABLE, 
	"REFRESH_TOKEN_HASH" VARCHAR2(255), 
	"IS_ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"LAST_LOGIN" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"EMAIL_ADDRESS" VARCHAR2(255), 
	"INSTANCE" VARCHAR2(20), 
	"FND_USER_NAME" VARCHAR2(100), 
	 CONSTRAINT "CHK_USER_ROLE" CHECK (role IN ('admin','user')) ENABLE, 
	 CONSTRAINT "CHK_USER_ACTIVE" CHECK (is_active IN (0,1)) ENABLE, 
	 PRIMARY KEY ("USER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_USER_INITIALS" UNIQUE ("INITIALS")
  USING INDEX  ENABLE
   ) ;
CREATE UNIQUE INDEX "IDX_CRMS_USERS_FND" ON "CRMS_USERS" (UPPER("FND_USER_NAME")) 
  ;

CREATE INDEX "IDX_CRM_USERS_IS_ACTIVE" ON "CRMS_USERS" ("IS_ACTIVE") 
  ;
