-- CRMS_APPROVAL_FLOWS
CREATE TABLE "CRMS_APPROVAL_FLOWS" 
   (	"FLOW_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MODULE_ID" NUMBER NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"LEVEL_ORDER" NUMBER(2,0) NOT NULL ENABLE, 
	"APPROVER_USER_ID" NUMBER, 
	"AUTO_APPROVE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"FLOW_TYPE" VARCHAR2(10) DEFAULT 'RD' NOT NULL ENABLE, 
	 PRIMARY KEY ("FLOW_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_AF_FLOW_TYPE" CHECK (flow_type IN ('RD','FSD')) ENABLE, 
	 CONSTRAINT "UQ_AF_PHASE_LEVEL" UNIQUE ("MODULE_ID", "PHASE_CODE", "LEVEL_ORDER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_AF_PHASE" CHECK (phase_code IN ('DRAFT','RD','FSD','DEPLOYMENT','DBA_DEPLOYMENT','OBSERVATION')) ENABLE, 
	 CONSTRAINT "FK_AF_MODULE" FOREIGN KEY ("MODULE_ID")
	  REFERENCES "CRMS_MODULES" ("MODULE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_AF_USER" FOREIGN KEY ("APPROVER_USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_AF_MODULE" ON "CRMS_APPROVAL_FLOWS" ("MODULE_ID") 
  ;
