-- CRMS_AUDIT
CREATE TABLE "CRMS_AUDIT" 
   (	"AUDIT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ACTION" VARCHAR2(50) NOT NULL ENABLE, 
	"PERFORMED_BY" NUMBER NOT NULL ENABLE, 
	"CR_NUMBER" VARCHAR2(20) DEFAULT '--' NOT NULL ENABLE, 
	"DETAILS" VARCHAR2(1000), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("AUDIT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_AUDIT_USER" FOREIGN KEY ("PERFORMED_BY")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_AUDIT_ACTION" ON "CRMS_AUDIT" ("ACTION") 
  ;

CREATE INDEX "IDX_AUDIT_CREATEDT" ON "CRMS_AUDIT" ("CREATED_AT" DESC) 
  ;

CREATE INDEX "IDX_AUDIT_CRNUM" ON "CRMS_AUDIT" ("CR_NUMBER") 
  ;

CREATE INDEX "IDX_AUDIT_USER" ON "CRMS_AUDIT" ("PERFORMED_BY") 
  ;
