-- CRMS_GROUP_MEMBERS
CREATE TABLE "CRMS_GROUP_MEMBERS" 
   (	"GROUP_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"JOINED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "PK_GROUP_MEMBERS" PRIMARY KEY ("GROUP_ID", "USER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_GM_GROUP" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "CRMS_ASSIGNMENT_GROUPS" ("GROUP_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_GM_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ON DELETE CASCADE ENABLE
   ) ;
