-- CRMS_MODULE_USERS
CREATE TABLE "CRMS_MODULE_USERS" 
   (	"MODULE_USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MODULE_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"IS_REQUESTER" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"IS_APPROVER" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CHK_MU_REQ" CHECK (is_requester IN (0,1)) ENABLE, 
	 CONSTRAINT "CHK_MU_APP" CHECK (is_approver IN (0,1)) ENABLE, 
	 PRIMARY KEY ("MODULE_USER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_MODULE_USER" UNIQUE ("MODULE_ID", "USER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_MU_MODULE" FOREIGN KEY ("MODULE_ID")
	  REFERENCES "CRMS_MODULES" ("MODULE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_MU_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ON DELETE CASCADE ENABLE
   ) ;
CREATE INDEX "IDX_MU_MODULE" ON "CRMS_MODULE_USERS" ("MODULE_ID") 
  ;

CREATE INDEX "IDX_MU_USER" ON "CRMS_MODULE_USERS" ("USER_ID") 
  ;
