-- CRMS_PHASE_PROCESS_OWNERS
CREATE TABLE "CRMS_PHASE_PROCESS_OWNERS" 
   (	"PO_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MODULE_ID" NUMBER NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"GROUP_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("PO_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_PO" UNIQUE ("MODULE_ID", "PHASE_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_PO_GROUP" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "CRMS_ASSIGNMENT_GROUPS" ("GROUP_ID") ENABLE, 
	 CONSTRAINT "FK_PO_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
