-- CRMS_PHASE_REVIEWERS
CREATE TABLE "CRMS_PHASE_REVIEWERS" 
   (	"REVIEWER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MODULE_ID" NUMBER NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"GROUP_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("REVIEWER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_PR_GROUP" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "CRMS_ASSIGNMENT_GROUPS" ("GROUP_ID") ENABLE, 
	 CONSTRAINT "FK_PR_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
