-- CRMS_PHASE_TEMPLATES
CREATE TABLE "CRMS_PHASE_TEMPLATES" 
   (	"TEMPLATE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"MODULE_ID" NUMBER NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(500) NOT NULL ENABLE, 
	"FILE_TYPE" VARCHAR2(200), 
	"FILE_DATA" CLOB NOT NULL ENABLE, 
	"UPLOADED_BY" NUMBER NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("TEMPLATE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_PHASE_TEMPLATE" UNIQUE ("MODULE_ID", "PHASE_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_PT_PHASE" CHECK (phase_code IN ('RD','FSD','DEV','TESTING','UAT','DEPLOYMENT','DBA_DEPLOYMENT','OBSERVATION')) ENABLE, 
	 CONSTRAINT "FK_PT_MODULE" FOREIGN KEY ("MODULE_ID")
	  REFERENCES "CRMS_MODULES" ("MODULE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_PT_USER" FOREIGN KEY ("UPLOADED_BY")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_PT_MODULE" ON "CRMS_PHASE_TEMPLATES" ("MODULE_ID") 
  ;
