-- CRMS_RELEASES
CREATE TABLE "CRMS_RELEASES" 
   (	"RELEASE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"RELEASE_NUMBER" VARCHAR2(20) NOT NULL ENABLE, 
	"STATE" VARCHAR2(60) DEFAULT 'Draft' NOT NULL ENABLE, 
	"PRIORITY" VARCHAR2(1) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(200) NOT NULL ENABLE, 
	"SUMMARY" CLOB, 
	"COMPANY" VARCHAR2(200), 
	"SERVICE" VARCHAR2(200), 
	"PLANNED_START_DATE" DATE, 
	"TARGET_END_DATE" DATE, 
	"REQUESTED_BY" NUMBER NOT NULL ENABLE, 
	"ASSIGNMENT_GROUP_ID" NUMBER, 
	"ASSIGNED_TO_USER_ID" NUMBER, 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"MODULE_ID" NUMBER, 
	"CURRENT_APPROVAL_LEVEL" NUMBER DEFAULT 0, 
	"CR_OWNER_USER_ID" NUMBER, 
	"CEMLI" VARCHAR2(200), 
	"SMARTSHEET_ID" VARCHAR2(200), 
	"PROCESS_NAME" VARCHAR2(500), 
	"REASON_OF_CHANGE" VARCHAR2(1000), 
	"BUSINESS_BENEFITS_PROCESS" VARCHAR2(1000), 
	"BUSINESS_BENEFITS_QUALITATIVE" VARCHAR2(1000), 
	"COST_SAVING" VARCHAR2(1000), 
	"MANPOWER_SAVING" VARCHAR2(1000), 
	 CONSTRAINT "CHK_RELEASE_PRIORITY" CHECK (priority IN ('1','2','3','4')) ENABLE, 
	 CONSTRAINT "CHK_RELEASE_DELETED" CHECK (is_deleted IN (0,1)) ENABLE, 
	 CONSTRAINT "CHK_RELEASE_DATES" CHECK (
          target_end_date IS NULL OR target_end_date >= planned_start_date
        ) ENABLE, 
	 PRIMARY KEY ("RELEASE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_RELEASE_NUMBER" UNIQUE ("RELEASE_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_RELEASE_STATE" CHECK (state IN ('RD Phase','RD Awaiting Approval L1','RD Awaiting Approval L2','RD Awaiting Approval L3','RD Awaiting Approval L4','RD Awaiting Approval L5','RD Approval L1','RD Approval L2','RD Approval L3','RD Approval L4','RD Approval L5','FSD Phase','FSD Awaiting Approval L1','FSD Awaiting Approval L2','FSD Awaiting Approval L3','FSD Awaiting Approval L4','FSD Awaiting Approval L5','FSD Approval L1','FSD Approval L2','FSD Approval L3','FSD Approval L4','FSD Approval L5','Development Phase','Testing Phase','UAT Phase','Deployment Phase','Deployment Approval L1','Deployment Approval L2','Deployment Approval L3','Deployment Approval L4','Deployment Approval L5','DBA Deployment Phase','Observation Phase','On Hold','Closed','Cancelled')) ENABLE, 
	 CONSTRAINT "FK_REL_REQUESTED_BY" FOREIGN KEY ("REQUESTED_BY")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_REL_AG" FOREIGN KEY ("ASSIGNMENT_GROUP_ID")
	  REFERENCES "CRMS_ASSIGNMENT_GROUPS" ("GROUP_ID") ENABLE, 
	 CONSTRAINT "FK_REL_ASSIGNED_TO" FOREIGN KEY ("ASSIGNED_TO_USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_REL_CR_OWNER" FOREIGN KEY ("CR_OWNER_USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_REL_AG" ON "CRMS_RELEASES" ("ASSIGNMENT_GROUP_ID") 
  ;

CREATE INDEX "IDX_REL_CR_OWNER" ON "CRMS_RELEASES" ("CR_OWNER_USER_ID") 
  ;

CREATE INDEX "IDX_REL_DELETED" ON "CRMS_RELEASES" ("IS_DELETED") 
  ;

CREATE INDEX "IDX_REL_PRIORITY" ON "CRMS_RELEASES" ("PRIORITY") 
  ;

CREATE INDEX "IDX_REL_REQBY" ON "CRMS_RELEASES" ("REQUESTED_BY") 
  ;

CREATE INDEX "IDX_REL_STARTDT" ON "CRMS_RELEASES" ("PLANNED_START_DATE") 
  ;

CREATE INDEX "IDX_REL_STATE" ON "CRMS_RELEASES" ("STATE") 
  ;
