-- CRMS_ATTACHMENTS
CREATE TABLE "CRMS_ATTACHMENTS" 
   (	"ATTACHMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"RELEASE_ID" NUMBER NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(500) NOT NULL ENABLE, 
	"FILE_TYPE" VARCHAR2(200), 
	"FILE_SIZE" NUMBER, 
	"FILE_DATA" CLOB NOT NULL ENABLE, 
	"UPLOADED_BY" NUMBER NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20), 
	"TASK_ID" NUMBER, 
	 PRIMARY KEY ("ATTACHMENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_ATT_RELEASE" FOREIGN KEY ("RELEASE_ID")
	  REFERENCES "CRMS_RELEASES" ("RELEASE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_ATT_USER" FOREIGN KEY ("UPLOADED_BY")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_ATT_RELEASE" ON "CRMS_ATTACHMENTS" ("RELEASE_ID") 
  ;

CREATE INDEX "IDX_ATT_USER" ON "CRMS_ATTACHMENTS" ("UPLOADED_BY") 
  ;
