-- CRMS_COMMENTS
CREATE TABLE "CRMS_COMMENTS" 
   (	"COMMENT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"RELEASE_ID" NUMBER NOT NULL ENABLE, 
	"COMMENT_TEXT" CLOB NOT NULL ENABLE, 
	"CREATED_BY" NUMBER NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("COMMENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_COMMENT_RELEASE" FOREIGN KEY ("RELEASE_ID")
	  REFERENCES "CRMS_RELEASES" ("RELEASE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_COMMENT_USER" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_COMMENT_RELEASE" ON "CRMS_COMMENTS" ("RELEASE_ID") 
  ;
