-- CRMS_NOTIFICATIONS
CREATE TABLE "CRMS_NOTIFICATIONS" 
   (	"NOTIFICATION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(500) NOT NULL ENABLE, 
	"IS_READ" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"RELEASE_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CHK_NOTIF_READ" CHECK (is_read IN (0,1)) ENABLE, 
	 PRIMARY KEY ("NOTIFICATION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_NOTIF_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_NOTIF_RELEASE" FOREIGN KEY ("RELEASE_ID")
	  REFERENCES "CRMS_RELEASES" ("RELEASE_ID") ON DELETE SET NULL ENABLE
   ) ;
CREATE INDEX "IDX_NOTIF_UNREAD" ON "CRMS_NOTIFICATIONS" ("USER_ID", "IS_READ") 
  ;

CREATE INDEX "IDX_NOTIF_USER" ON "CRMS_NOTIFICATIONS" ("USER_ID") 
  ;
