-- CRMS_RELEASE_APPROVALS
CREATE TABLE "CRMS_RELEASE_APPROVALS" 
   (	"APPROVAL_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"RELEASE_ID" NUMBER NOT NULL ENABLE, 
	"MODULE_ID" NUMBER NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"LEVEL_ORDER" NUMBER(2,0) NOT NULL ENABLE, 
	"APPROVER_USER_ID" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10) DEFAULT 'Pending' NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(2000), 
	"ACTIONED_AT" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"FLOW_TYPE" VARCHAR2(10) DEFAULT 'RD' NOT NULL ENABLE, 
	 CONSTRAINT "CHK_RA_STATUS" CHECK (status IN ('Pending','Approved','Rejected')) ENABLE, 
	 PRIMARY KEY ("APPROVAL_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_RA_RELEASE" FOREIGN KEY ("RELEASE_ID")
	  REFERENCES "CRMS_RELEASES" ("RELEASE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_RA_APPROVER" FOREIGN KEY ("APPROVER_USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_RA_APPROVER" ON "CRMS_RELEASE_APPROVALS" ("APPROVER_USER_ID", "STATUS") 
  ;

CREATE INDEX "IDX_RA_RELEASE" ON "CRMS_RELEASE_APPROVALS" ("RELEASE_ID") 
  ;
