-- CRMS_RELEASE_HISTORY
CREATE TABLE "CRMS_RELEASE_HISTORY" 
   (	"HISTORY_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"RELEASE_ID" NUMBER NOT NULL ENABLE, 
	"ACTION" VARCHAR2(50) NOT NULL ENABLE, 
	"FROM_STATE" VARCHAR2(60), 
	"TO_STATE" VARCHAR2(60) NOT NULL ENABLE, 
	"CHANGED_BY" NUMBER NOT NULL ENABLE, 
	"CHANGED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("HISTORY_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_HIST_RELEASE" FOREIGN KEY ("RELEASE_ID")
	  REFERENCES "CRMS_RELEASES" ("RELEASE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_HIST_USER" FOREIGN KEY ("CHANGED_BY")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_HIST_RELEASE" ON "CRMS_RELEASE_HISTORY" ("RELEASE_ID") 
  ;
