-- CRMS_RELEASE_PHASE_GROUPS
CREATE TABLE "CRMS_RELEASE_PHASE_GROUPS" 
   (	"RPG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"RELEASE_ID" NUMBER NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"GROUP_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("RPG_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_RPG" UNIQUE ("RELEASE_ID", "PHASE_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_RPG_RELEASE" FOREIGN KEY ("RELEASE_ID")
	  REFERENCES "CRMS_RELEASES" ("RELEASE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_RPG_GROUP" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "CRMS_ASSIGNMENT_GROUPS" ("GROUP_ID") ENABLE
   ) ;
