-- CRMS_RELEASE_TASKS
CREATE TABLE "CRMS_RELEASE_TASKS" 
   (	"TASK_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TASK_NUMBER" VARCHAR2(20) NOT NULL ENABLE, 
	"RELEASE_ID" NUMBER NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"ASSIGNED_TO" NUMBER NOT NULL ENABLE, 
	"STATE" VARCHAR2(10) DEFAULT 'Open' NOT NULL ENABLE, 
	"TEMPLATE_DOWNLOADED" NUMBER(1,0) DEFAULT 0, 
	"UPLOAD_ATTACHMENT_ID" NUMBER, 
	"SHORT_DESCRIPTION" VARCHAR2(500), 
	"CLOSED_BY" NUMBER, 
	"CLOSED_AT" TIMESTAMP (6), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"PLANNED_START_DATE" DATE, 
	"PLANNED_END_DATE" DATE, 
	"ACTUAL_START_DATE" DATE, 
	"ACTUAL_END_DATE" DATE, 
	"ASSIGNMENT_GROUP_ID" NUMBER, 
	"PRIORITY" VARCHAR2(1), 
	"DESCRIPTION" CLOB, 
	"REASON_FOR_REJECT" VARCHAR2(500), 
	"DELAY_REASON" VARCHAR2(2000), 
	"CEMLI" VARCHAR2(200), 
	"SMARTSHEET_ID" VARCHAR2(200), 
	"PROCESS_NAME" VARCHAR2(500), 
	 CONSTRAINT "CHK_RT_STATE" CHECK (state IN ('Open','Closed')) ENABLE, 
	 PRIMARY KEY ("TASK_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_RT_NUMBER" UNIQUE ("TASK_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_RT_PHASE" CHECK (phase_code IN ('RD','FSD','DEV','TESTING','UAT','DEPLOYMENT','DBA_DEPLOYMENT')) ENABLE, 
	 CONSTRAINT "FK_RT_RELEASE" FOREIGN KEY ("RELEASE_ID")
	  REFERENCES "CRMS_RELEASES" ("RELEASE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_RT_ASSIGNEE" FOREIGN KEY ("ASSIGNED_TO")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_RT_CLOSEDBY" FOREIGN KEY ("CLOSED_BY")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_RT_ASSIGNEE" ON "CRMS_RELEASE_TASKS" ("ASSIGNED_TO") 
  ;

CREATE INDEX "IDX_RT_PHASE" ON "CRMS_RELEASE_TASKS" ("RELEASE_ID", "PHASE_CODE") 
  ;

CREATE INDEX "IDX_RT_RELEASE" ON "CRMS_RELEASE_TASKS" ("RELEASE_ID") 
  ;
