-- CRMS_REVIEW_REQUESTS
CREATE TABLE "CRMS_REVIEW_REQUESTS" 
   (	"REVIEW_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"RELEASE_ID" NUMBER NOT NULL ENABLE, 
	"PHASE_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"SENT_BY" NUMBER NOT NULL ENABLE, 
	"REVIEWER_ID" NUMBER NOT NULL ENABLE, 
	"PASSED_TO" NUMBER, 
	"STATUS" VARCHAR2(20) DEFAULT 'Pending' NOT NULL ENABLE, 
	"NOTES" VARCHAR2(1000), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("REVIEW_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_RR_RELEASE" FOREIGN KEY ("RELEASE_ID")
	  REFERENCES "CRMS_RELEASES" ("RELEASE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_RR_SENT_BY" FOREIGN KEY ("SENT_BY")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_RR_REVIEWER" FOREIGN KEY ("REVIEWER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_RR_PASSED" FOREIGN KEY ("PASSED_TO")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_RR_RELEASE" ON "CRMS_REVIEW_REQUESTS" ("RELEASE_ID") 
  ;

CREATE INDEX "IDX_RR_REVIEWER" ON "CRMS_REVIEW_REQUESTS" ("REVIEWER_ID") 
  ;

CREATE INDEX "IDX_RR_STATUS" ON "CRMS_REVIEW_REQUESTS" ("STATUS") 
  ;
