-- CRMS_TASKS
CREATE TABLE "CRMS_TASKS" 
   (	"TASK_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TASK_NUMBER" VARCHAR2(20) NOT NULL ENABLE, 
	"RELEASE_ID" NUMBER NOT NULL ENABLE, 
	"PHASE" VARCHAR2(10) NOT NULL ENABLE, 
	"TASK_TYPE" VARCHAR2(30) NOT NULL ENABLE, 
	"STATE" VARCHAR2(10) DEFAULT 'Open' NOT NULL ENABLE, 
	"SHORT_DESCRIPTION" VARCHAR2(500) NOT NULL ENABLE, 
	"ASSIGNMENT_GROUP_ID" NUMBER, 
	"ASSIGNED_TO_USER_ID" NUMBER, 
	"CREATED_BY" NUMBER NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "CHK_TASK_PHASE" CHECK (phase IN ('BRD','FSD','Dev','Testing','UAT')) ENABLE, 
	 CONSTRAINT "CHK_TASK_STATE" CHECK (state IN ('Open','Closed')) ENABLE, 
	 PRIMARY KEY ("TASK_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_TASK_NUMBER" UNIQUE ("TASK_NUMBER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_TASK_RELEASE" FOREIGN KEY ("RELEASE_ID")
	  REFERENCES "CRMS_RELEASES" ("RELEASE_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_TASK_AG" FOREIGN KEY ("ASSIGNMENT_GROUP_ID")
	  REFERENCES "CRMS_ASSIGNMENT_GROUPS" ("GROUP_ID") ENABLE, 
	 CONSTRAINT "FK_TASK_ASSIGNED" FOREIGN KEY ("ASSIGNED_TO_USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE, 
	 CONSTRAINT "FK_TASK_CREATEDBY" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_TASK_ASSIGNED" ON "CRMS_TASKS" ("ASSIGNED_TO_USER_ID") 
  ;

CREATE INDEX "IDX_TASK_RELEASE" ON "CRMS_TASKS" ("RELEASE_ID") 
  ;

CREATE INDEX "IDX_TASK_STATE" ON "CRMS_TASKS" ("STATE") 
  ;
