-- CRMS_TASK_LIST
CREATE TABLE "CRMS_TASK_LIST" 
   (	"TASK_LIST_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"REPORTED_ON" VARCHAR2(50), 
	"REQUESTER" VARCHAR2(200), 
	"CEMLI" VARCHAR2(200), 
	"SERVICE_NOW_ID" VARCHAR2(200), 
	"TICKET_NO" VARCHAR2(200), 
	"SMART_SHEET" VARCHAR2(500), 
	"PROJECT" VARCHAR2(200), 
	"MODULE" VARCHAR2(200), 
	"PROCESS" VARCHAR2(200), 
	"TASK_TITLE" VARCHAR2(1000), 
	"OWNER" VARCHAR2(200), 
	"STATUS" VARCHAR2(50) DEFAULT 'NOT STARTED', 
	"STAGE" VARCHAR2(100), 
	"PENDING_WITH" VARCHAR2(200), 
	"CR_TASK_ID" VARCHAR2(200), 
	"CR_NUMBER" VARCHAR2(50), 
	"AUTO_POPULATED" NUMBER(1,0) DEFAULT 0, 
	"CREATED_BY" NUMBER NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"IS_DELETED" NUMBER(1,0) DEFAULT 0, 
	"DELAY_REASON" VARCHAR2(1000), 
	"COMMENTS" VARCHAR2(2000), 
	"TRACKER_COMMENTS" VARCHAR2(2000), 
	"RD_APPROVAL_DT" VARCHAR2(50), 
	"MD50_ST" VARCHAR2(50), 
	"MD50_END" VARCHAR2(50), 
	"MD50_APP_BY" VARCHAR2(200), 
	"MD50_APP_ON" VARCHAR2(50), 
	"DEV_ST" VARCHAR2(50), 
	"DEV_END" VARCHAR2(50), 
	"TFT_ST" VARCHAR2(50), 
	"TFT_END" VARCHAR2(50), 
	"UAT_CLOSED_ON" VARCHAR2(50), 
	"APPROVED1_ON" VARCHAR2(50), 
	"APPROVED2_ON" VARCHAR2(50), 
	"APPROVED3_ON" VARCHAR2(50), 
	"DEPLOYED_SAMIL" VARCHAR2(50), 
	"DEPLOYED_MSWIL" VARCHAR2(50), 
	"CR_OWNER" VARCHAR2(200), 
	 CONSTRAINT "CHK_TL_STATUS" CHECK (status IN (
                             'OPEN','HOLD','DROP','COMPLETE','NOT STARTED'
                           )) ENABLE, 
	 CONSTRAINT "CHK_TL_AUTO" CHECK (auto_populated IN (0,1)) ENABLE, 
	 CONSTRAINT "CHK_TL_DELETED" CHECK (is_deleted IN (0,1)) ENABLE, 
	 PRIMARY KEY ("TASK_LIST_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_TL_CREATED_BY" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
CREATE INDEX "IDX_TL_CREATED_BY" ON "CRMS_TASK_LIST" ("CREATED_BY") 
  ;

CREATE INDEX "IDX_TL_CR_NUMBER" ON "CRMS_TASK_LIST" ("CR_NUMBER") 
  ;

CREATE INDEX "IDX_TL_CR_TASK_ID" ON "CRMS_TASK_LIST" ("CR_TASK_ID") 
  ;

CREATE INDEX "IDX_TL_STATUS" ON "CRMS_TASK_LIST" ("STATUS") 
  ;
