-- CRMS_TASK_LIST_EDITORS
CREATE TABLE "CRMS_TASK_LIST_EDITORS" 
   (	"EDITOR_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"ADDED_BY" NUMBER NOT NULL ENABLE, 
	"ADDED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	 PRIMARY KEY ("EDITOR_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_TL_EDITOR" UNIQUE ("USER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_TL_EDITOR_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_TL_EDITOR_ADDEDBY" FOREIGN KEY ("ADDED_BY")
	  REFERENCES "CRMS_USERS" ("USER_ID") ENABLE
   ) ;
