-- USER_SESSIONS
CREATE TABLE "USER_SESSIONS" 
   (	"SESSION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"INSTANCE" VARCHAR2(50) DEFAULT 'PRIMARY' NOT NULL ENABLE, 
	"REFRESH_TOKEN_HASH" VARCHAR2(64) NOT NULL ENABLE, 
	"DEVICE_ID" VARCHAR2(100), 
	"DEVICE_NAME" VARCHAR2(100), 
	"BROWSER" VARCHAR2(100), 
	"OPERATING_SYSTEM" VARCHAR2(100), 
	"IP_ADDRESS" VARCHAR2(50), 
	"USER_AGENT" VARCHAR2(500), 
	"STATUS" VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL ENABLE, 
	"LOGOUT_REASON" VARCHAR2(100), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"LAST_ACTIVITY" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"LAST_REFRESH_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"ABSOLUTE_EXPIRES_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP + INTERVAL '8' HOUR NOT NULL ENABLE, 
	"REVOKED_AT" TIMESTAMP (6), 
	"SESSION_EXPIRES_AT" TIMESTAMP (6), 
	 CONSTRAINT "CHK_SESSION_INSTANCE" CHECK (instance IN ('PRIMARY', 'SECONDARY')) ENABLE, 
	 PRIMARY KEY ("SESSION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CHK_SESSION_STATUS" CHECK (status IN ('ACTIVE', 'REVOKED', 'EXPIRED')) ENABLE, 
	 CONSTRAINT "FK_SESSION_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "CRMS_USERS" ("USER_ID") ON DELETE CASCADE ENABLE
   ) ;
CREATE INDEX "IDX_SESSIONS_EXPIRES" ON "USER_SESSIONS" ("SESSION_EXPIRES_AT") 
  ;

CREATE INDEX "IDX_SESSION_STATUS" ON "USER_SESSIONS" ("STATUS") 
  ;

CREATE INDEX "IDX_SESSION_TOKEN_HASH" ON "USER_SESSIONS" ("REFRESH_TOKEN_HASH") 
  ;

CREATE INDEX "IDX_SESSION_USER" ON "USER_SESSIONS" ("USER_ID") 
  ;
