-- TRG_TASKS_UPDATED_AT
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_TASKS_UPDATED_AT" 
            BEFORE UPDATE ON crms_tasks
            FOR EACH ROW
          BEGIN
            :NEW.updated_at := SYSTIMESTAMP;
          END;
/
ALTER TRIGGER "TRG_TASKS_UPDATED_AT" ENABLE;
