-- TRG_RELEASES_UPDATED_AT
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_RELEASES_UPDATED_AT" 
            BEFORE UPDATE ON crms_releases
            FOR EACH ROW
          BEGIN
            :NEW.updated_at := SYSTIMESTAMP;
          END;
/
ALTER TRIGGER "TRG_RELEASES_UPDATED_AT" ENABLE;
