-- TRG_TASK_LIST_UPDATED_AT
CREATE OR REPLACE NONEDITIONABLE TRIGGER "TRG_TASK_LIST_UPDATED_AT" 
  BEFORE UPDATE ON crms_task_list
  FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;

/
ALTER TRIGGER "TRG_TASK_LIST_UPDATED_AT" ENABLE;
